void inicio();
void fin();
void leyendoTipoString(int);
void CrearVariable(char*,char*);
void concatenaOperacion (char*, char*, char*, char*);
void imprimir(char*);
void importChait();
void imprimirVariable(char*, char*);
void imprimirTexto(char*, char*);
void validacionIf(char*);
void FinalIfCiclo();