void inicio();
void fin();
void leyendoTipoString(int);
void CrearVariable(char*,char*);
void concatenaOperacion (char*, char*, char*, char*);
void imprimir(char*);
void importChait();
void imprimirVariable(char*, char*);
void imprimirTexto(char*, char*);
void validacionIf(char*);
void validarVariableCondicional(char*, int, int);
void encabezadoIf(char*, int);
void encabezadoWhile(char*, int);
void encabezadoFor(char*, int);
void encabezadoElse();
void FinalFor(char*);
void FinalIfCiclo();
void tabulacion();
void funcionConcatenar(char*,char*,int);
void funcionUpper(char*, int);